### ISSUE TITLE
Project submission form + Milestones

### ISSUE THREAD

**Issue by lewisMW** [lewisMW/agriculture-SoC#3]
Fill out the project submission form and milestones [here](https://unisydneyedu-my.sharepoint.com/:w:/g/personal/lwat0045_uni_sydney_edu_au/ETINbAPwxZhPrn57SC2FBakBDUp79QfLtQkZGyDaJh7H_g?e=DN0rt0).
- Body: Hee, Jaime, Shin
- Milestones: Patrick, KeZhi, Erick, Adrian, Daniel, Josh

**Comment by pgaft** [comment]
Milestone: Determine which ARM IP are applicable to our design.

**Comment by pgaft** [comment]
Milestone: Determine project scope and focus.

**Comment by pgaft** [comment]
Generic Milestone: <ARM IP> implementation and interfacing

**Comment by womba** [comment]
Milestone: Verification of Digital Design?

**Comment by womba** [comment]
Milestone: Software configuration and programming.

**Comment by AbacusIsMad** [comment]
Milestone: run example design flow using cortex-M0 (placeholder) and GPIO for familiarity
